[[redirects]]
from = "/contact"
to = "https://discord.com/invite/wadnsfw"

  [[redirects]]
  from = "/appeal.html"
  to = "https://appeal.gg/wadnsfw"

[[redirects]]
  from = "/*"
  to = "/index"

  [[redirects]]
  from = "/images"
  to = "/index"
