
[[redirects]]
  from = "/*"
  to = "/index"

  [[redirects]]
  from = "/"
  to = "/index"

  [[redirects]]
  from = ""
  to = "/index"

  [[redirects]]
  from = "/images"
  to = "/index"
